name: msBlock
version: ${project.version}
description: A Minecraft plugin with Blocks for "Unknown server"
authors: [MinersStudios, p0loskun]
website: minersstudios.github.io

main: github.minersStudios.Main
api-version: 1.18
database: false
softdepend:
  - CoreProtect
  - ProtocolLib
